// Code generated by `make refresh-pin`. DO NOT EDIT.

package version

// Pinned is the upstream release without the leading "v".
// Mirrors the require entry for ModulePath in the repo's go.mod.
const Pinned = "1.2.1"
