// Package version exposes the agentgateway upstream release this build
// of muster targets. Pinned mirrors the require entry for ModulePath in
// the repo's go.mod, regenerated by `make refresh-pin`. Every other
// agentgateway-version reference (the subprocess binary, the
// native-config schema URL, the CRD type aliases) derives from Pinned,
// so a Renovate bump of go.mod plus `make refresh-agentgateway` is the
// whole update step. `make verify-agentgateway` catches drift in CI and
// pre-commit.
//
// Reading go.mod at runtime instead of mirroring it is not viable: Go's
// `//go:embed` rejects symlinks and ancestor paths, and
// `runtime/debug.ReadBuildInfo` leaves `info.Deps` empty in `go test`
// binaries, so a single-source-at-runtime approach would break the test
// suite that consumes Pinned to build asset URLs.
package version

// ModulePath is the Go import path of the upstream module that drives
// Pinned.
const ModulePath = "github.com/agentgateway/agentgateway"

// Tag is Pinned prefixed with "v" — the form used by git tags, GitHub
// release paths, and the upstream schema URL.
var Tag = "v" + Pinned
