# Custom Makefile targets for muster
# This file is included by the main Makefile via `include Makefile.*.mk`

##@ Release

.PHONY: release-dry-run
release-dry-run: ## Test the release process without publishing (all platforms)
	goreleaser release --snapshot --clean --skip=announce,publish,validate

.PHONY: release-dry-run-fast
release-dry-run-fast: ## Fast release dry-run for CI (linux/amd64 only, ~6min faster)
	goreleaser release --config .goreleaser.ci.yaml --snapshot --clean --skip=announce,publish,validate

.PHONY: release-local
release-local: ## Create a release locally
	goreleaser release --clean

##@ Development

.PHONY: lint-yaml
lint-yaml: ## Run YAML linter
	@echo "Running YAML linter..."
	@# Exclude zz_generated files
	@yamllint .github/workflows/auto-release.yaml .github/workflows/ci.yaml .goreleaser.yaml .goreleaser.ci.yaml

.PHONY: helm-lint
helm-lint: ## Run Helm linter
	@echo "Running Helm linter..."
	@helm lint helm/muster/

.PHONY: helm-test
helm-test: ## Run Helm unit tests (requires helm-unittest plugin)
	@echo "Running Helm unit tests..."
	@helm unittest helm/muster/

.PHONY: check
check: lint-yaml helm-lint ## Run YAML and Helm linters

##@ Testing

.PHONY: test-vet
test-vet: ## Run go test and go vet
	@echo "Running Go tests (with NO_COLOR=true)..."
	@NO_COLOR=true go test -cover ./...
	@echo "Running go vet..."
	@go vet ./...

.PHONY: govulncheck
govulncheck: ## Run govulncheck to scan for known vulnerabilities
	@echo "Checking for known vulnerabilities..."
	@command -v govulncheck >/dev/null 2>&1 || { echo "Installing govulncheck..."; go install golang.org/x/vuln/cmd/govulncheck@latest; }
	@govulncheck ./...

AGENTGATEWAY_VERSION = $(shell go list -m -f '{{.Version}}' github.com/agentgateway/agentgateway | sed 's/^v//')
AGENTGATEWAY_ASSETS  = agentgateway-linux-amd64 agentgateway-linux-arm64 agentgateway-darwin-arm64 agentgateway-windows-amd64.exe
AGENTGATEWAY_PIN     = internal/agentgateway/version/pin.go

.PHONY: refresh-pin
refresh-pin: ## Regenerate $(AGENTGATEWAY_PIN) from the agentgateway version in go.mod.
	@set -euo pipefail; \
	version="$(AGENTGATEWAY_VERSION)"; \
	if [ -z "$$version" ]; then echo "could not read agentgateway version from go.mod"; exit 1; fi; \
	tmp=$$(mktemp); \
	{ \
		echo "// Code generated by \`make refresh-pin\`. DO NOT EDIT."; echo; \
		echo "package version"; echo; \
		echo "// Pinned is the upstream release without the leading \"v\"."; \
		echo "// Mirrors the require entry for ModulePath in the repo's go.mod."; \
		echo "const Pinned = \"$$version\""; \
	} > "$$tmp"; \
	gofmt -w "$$tmp"; \
	mv "$$tmp" "$(AGENTGATEWAY_PIN)"; \
	echo "wrote $(AGENTGATEWAY_PIN) for agentgateway v$$version"

.PHONY: verify-pin
verify-pin: ## Fail if $(AGENTGATEWAY_PIN) is out of sync with go.mod.
	@set -euo pipefail; \
	want="$(AGENTGATEWAY_VERSION)"; \
	got=$$(awk -F'"' '/^const Pinned/ {print $$2}' $(AGENTGATEWAY_PIN)); \
	if [ "$$want" != "$$got" ]; then \
		echo "$(AGENTGATEWAY_PIN) Pinned=$$got but go.mod has v$$want — run \`make refresh-pin\`"; exit 1; \
	fi; \
	echo "OK $(AGENTGATEWAY_PIN) matches go.mod ($$want)"

.PHONY: verify-checksums
verify-checksums: ## Diff pinned agentgateway SHA-256 constants against upstream release .sha256 files.
	@set -euo pipefail; \
	version="$(AGENTGATEWAY_VERSION)"; \
	if [ -z "$$version" ]; then echo "could not read agentgateway version from go.mod"; exit 1; fi; \
	echo "Verifying pinned checksums against agentgateway v$$version..."; \
	rc=0; \
	for asset in $(AGENTGATEWAY_ASSETS); do \
		upstream=$$(curl -fsSL "https://github.com/agentgateway/agentgateway/releases/download/v$${version}/$${asset}.sha256" | awk '{print $$1}'); \
		pinned=$$(awk -v key="\"$${asset}\":" '$$1==key {gsub(/[",]/,"",$$2); print $$2}' internal/agentgateway/binary/checksums.go); \
		if [ -z "$$pinned" ]; then echo "MISSING pinned entry for $$asset"; rc=1; continue; fi; \
		if [ "$$upstream" != "$$pinned" ]; then \
			echo "MISMATCH $$asset: upstream=$$upstream pinned=$$pinned"; rc=1; \
		else \
			echo "OK       $$asset $$pinned"; \
		fi; \
	done; \
	exit $$rc

.PHONY: refresh-checksums
refresh-checksums: ## Regenerate internal/agentgateway/binary/checksums.go from upstream .sha256 files at the version pinned in go.mod.
	@set -euo pipefail; \
	version="$(AGENTGATEWAY_VERSION)"; \
	if [ -z "$$version" ]; then echo "could not read agentgateway version from go.mod"; exit 1; fi; \
	out=internal/agentgateway/binary/checksums.go; \
	tmp=$$(mktemp); \
	{ \
		echo "package binary"; echo; \
		echo "// pinnedChecksums maps the upstream asset filename to the hex-encoded"; \
		echo "// SHA-256 of that asset for the agentgateway release named by"; \
		echo "// PinnedVersion (driven by go.mod). Regenerate with"; \
		echo "// \`make refresh-checksums\` after \`go get github.com/agentgateway/agentgateway@vX.Y.Z\`."; \
		echo "var pinnedChecksums = map[string]string{"; \
		for asset in $(AGENTGATEWAY_ASSETS); do \
			digest=$$(curl -fsSL "https://github.com/agentgateway/agentgateway/releases/download/v$${version}/$${asset}.sha256" | awk '{print $$1}'); \
			if [ -z "$$digest" ]; then echo "failed to fetch digest for $$asset" >&2; exit 1; fi; \
			printf '\t%-34s "%s",\n' "\"$$asset\":" "$$digest"; \
		done; \
		echo "}"; \
	} > "$$tmp"; \
	gofmt -w "$$tmp"; \
	mv "$$tmp" "$$out"; \
	echo "wrote $$out for agentgateway v$$version"

.PHONY: refresh-agentgateway
refresh-agentgateway: refresh-pin refresh-checksums ## Refresh every in-repo agentgateway version artifact from go.mod.

.PHONY: verify-agentgateway
verify-agentgateway: verify-pin verify-checksums ## Verify every in-repo agentgateway version artifact matches go.mod and upstream.

# Note: These targets require Docker and 'act' to be installed.
# See: https://github.com/nektos/act#installation

.PHONY: test-ci-pr
test-ci-pr: ## Run 'act' to simulate CI checks for a pull request
	@echo "Simulating CI workflow (pull_request event)..."
	@act pull_request --job check

.PHONY: test-ci-push
test-ci-push: ## Run 'act' to simulate CI checks for a push to main
	@echo "Simulating CI workflow (push event)..."
	@act push --job check

.PHONY: test-auto-release
test-auto-release: ## Run 'act' to simulate the auto-release workflow
	@echo "Simulating Auto-Release workflow (merged pull_request event)..."
	@echo "NOTE: Requires 'merged_pr_event.json' in the project root."
	@echo "NOTE: Git push steps within the workflow are expected to fail locally."
	@act pull_request --job auto_release --eventpath merged_pr_event.json
