package scale

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

const generatedHeader = "Generated by `go generate ./internal/testing/fixtures/scale/` from the shape in shape.go. DO NOT EDIT."

// RenderPreConfiguration renders the fixture as the pre_configuration
// fragment the harness loads through `pre_configuration.fixture: scale`:
// the two mock authorization servers, the broker trusting the fleet issuer,
// every server as a mock with its tools, every workflow. The capability
// documents are written once under `documents` and referenced by YAML alias
// from the servers that offer them, so the file is proportional to the
// distinct documents, like the store the fixture is about.
func RenderPreConfiguration(f *Fixture) ([]byte, error) {
	docs := map[string]*yaml.Node{}
	documents := &yaml.Node{Kind: yaml.MappingNode}
	for _, d := range f.Documents {
		seq := &yaml.Node{Kind: yaml.SequenceNode, Anchor: d.Name}
		for _, t := range d.Tools {
			seq.Content = append(seq.Content, toolNode(t))
		}
		docs[d.Name] = seq
		documents.Content = append(documents.Content, scalar(d.Name), seq)
	}

	servers := &yaml.Node{Kind: yaml.SequenceNode}
	for _, s := range f.Servers {
		servers.Content = append(servers.Content, serverNode(s, docs[s.Document]))
	}
	workflows := &yaml.Node{Kind: yaml.SequenceNode}
	for _, w := range f.Workflows {
		workflows.Content = append(workflows.Content, workflowNode(w))
	}

	root := mapping(
		"documents", withComment(documents, "The distinct capability documents; a server's tools alias one of them. The harness ignores this key."),
		"mock_oauth_servers", seq(
			mapping(
				"name", scalar(f.MusterOAuthServer),
				"scopes", seq(scalar("openid"), scalar("profile"), scalar("email"), scalar("groups")),
				"auto_approve", boolean(true),
				"pkce_required", boolean(false),
				"token_lifetime", scalar("1h"),
				"client_id", scalar("fixture-client"),
				"client_secret", scalar("fixture-secret"),
				"use_as_muster_oauth_server", boolean(true),
			),
			mapping("name", scalar(f.FleetIssuer)),
		),
		"muster_broker", mapping(
			"trusted_issuers", seq(mapping(
				"oauth_server_ref", scalar(f.FleetIssuer),
				"accepted_typ_headers", seq(scalar("")),
			)),
		),
		"mcp_servers", servers,
		"workflows", workflows,
	)
	shape := f.Shape()
	root.HeadComment = fmt.Sprintf("%s\n\nThe installation-shaped scale fixture: %d MCPServers (%d session-authenticated, %d families on %d installations, %d in-house), %d capability documents, %d workflows. Every name is invented.",
		generatedHeader, shape.Servers, shape.SessionAuthServers, shape.Families, shape.Installations, shape.Servers-shape.SessionAuthServers, shape.Documents, shape.Workflows)
	return encode(root)
}

// RenderSessions renders the session records.
func RenderSessions(f *Fixture) ([]byte, error) {
	sessions := &yaml.Node{Kind: yaml.SequenceNode}
	for _, s := range f.Sessions {
		sessions.Content = append(sessions.Content, mapping("id", scalar(s.ID), "subject", scalar(s.Subject)))
	}
	root := mapping("sessions", sessions)
	root.HeadComment = fmt.Sprintf("%s\n\n%d session records, one per forwarded bearer; every session is authenticated to every session-authenticated server of the fixture.",
		generatedHeader, len(f.Sessions))
	return encode(root)
}

func encode(root *yaml.Node) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return nil, fmt.Errorf("encode fixture: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("encode fixture: %w", err)
	}
	return buf.Bytes(), nil
}

func toolNode(t Tool) *yaml.Node {
	props := &yaml.Node{Kind: yaml.MappingNode}
	for _, p := range t.Properties {
		props.Content = append(props.Content, scalar(p.Name), mapping("type", scalar("string"), "description", scalar(p.Description)))
	}
	schema := mapping("type", scalar("object"), "properties", props)
	if len(t.Required) > 0 {
		required := &yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle}
		for _, r := range t.Required {
			required.Content = append(required.Content, scalar(r))
		}
		schema.Content = append(schema.Content, scalar("required"), required)
	}
	node := mapping("name", scalar(t.Name), "description", scalar(t.Description))
	if t.ReadOnly {
		node.Content = append(node.Content, scalar("annotations"), mapping("read_only_hint", boolean(true)))
	} else {
		node.Content = append(node.Content, scalar("annotations"), mapping("destructive_hint", boolean(true)))
	}
	node.Content = append(node.Content,
		scalar("input_schema"), schema,
		scalar("responses"), seq(mapping("response", flow(mapping("ok", boolean(true), "tool", scalar(t.Name))))),
	)
	return node
}

func serverNode(s Server, doc *yaml.Node) *yaml.Node {
	config := mapping("type", scalar("streamable-http"))
	if s.SessionAuth {
		config.Content = append(config.Content,
			scalar("oauth"), flow(mapping("required", boolean(true), "trust_issuer_ref", scalar(fleetIssuer), "forward_token", boolean(true))),
		)
	}
	if s.Family != "" {
		config.Content = append(config.Content,
			scalar("family"), flow(mapping("name", scalar(s.Family), "instanceArg", scalar(s.InstanceArg))),
		)
	}
	config.Content = append(config.Content, scalar("tools"), &yaml.Node{Kind: yaml.AliasNode, Alias: doc, Value: doc.Anchor})
	return mapping("name", scalar(s.Name), "config", config)
}

func workflowNode(w Workflow) *yaml.Node {
	args := &yaml.Node{Kind: yaml.MappingNode}
	for _, a := range w.Args {
		args.Content = append(args.Content, scalar(a.Name), flow(mapping("type", scalar(a.Type), "required", boolean(a.Required), "description", scalar(a.Description))))
	}
	steps := &yaml.Node{Kind: yaml.SequenceNode}
	for _, st := range w.Steps {
		stepArgs := &yaml.Node{Kind: yaml.MappingNode, Style: yaml.FlowStyle}
		for _, a := range st.Args {
			stepArgs.Content = append(stepArgs.Content, scalar(a.Name), scalar(a.Value))
		}
		steps.Content = append(steps.Content, mapping("id", scalar(st.ID), "tool", scalar(st.Tool), "args", stepArgs, "store", boolean(true)))
	}
	labels := &yaml.Node{Kind: yaml.MappingNode, Style: yaml.FlowStyle}
	for _, k := range sortedKeys(w.Labels) {
		labels.Content = append(labels.Content, scalar(k), scalar(w.Labels[k]))
	}
	return mapping(
		"name", scalar(w.Name),
		"labels", labels,
		"config", mapping(
			"name", scalar(w.Name),
			"description", scalar(w.Description),
			"args", args,
			"steps", steps,
		),
	)
}

// mapping builds a mapping node from alternating keys and values: a string is
// a scalar key (or value), a *yaml.Node is used as it is.
func mapping(kv ...any) *yaml.Node {
	node := &yaml.Node{Kind: yaml.MappingNode, Content: make([]*yaml.Node, 0, len(kv))}
	for _, item := range kv {
		switch v := item.(type) {
		case string:
			node.Content = append(node.Content, scalar(v))
		case *yaml.Node:
			node.Content = append(node.Content, v)
		default:
			panic(fmt.Sprintf("mapping: unsupported %T", item))
		}
	}
	return node
}

func seq(items ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Content: items}
}

func flow(n *yaml.Node) *yaml.Node {
	n.Style = yaml.FlowStyle
	return n
}

func withComment(n *yaml.Node, comment string) *yaml.Node {
	n.HeadComment = comment
	return n
}

func scalar(s string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: s}
}

func boolean(b bool) *yaml.Node {
	v := "false"
	if b {
		v = "true"
	}
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: v}
}
