package v1alpha1

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"
)

// loadGeneratedMCPServerCRD reads the generated CRD YAML from helm/muster/crds.
// The CRD file is the single source of truth checked into the repo and is
// regenerated by `make generate-crds`. These tests assert that the generated
// schema enforces what TB-0 and TB-8b promise.
func loadGeneratedMCPServerCRD(t *testing.T) *apiextensionsv1.CustomResourceDefinition {
	t.Helper()

	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..")
	crdPath := filepath.Join(repoRoot, "helm", "muster", "crds", "muster.giantswarm.io_mcpservers.yaml")

	// #nosec G304 -- crdPath is derived from runtime.Caller, not user input; fixed repo asset.
	raw, err := os.ReadFile(crdPath)
	if err != nil {
		t.Fatalf("failed to read CRD %s: %v", crdPath, err)
	}

	var crd apiextensionsv1.CustomResourceDefinition
	if err := yaml.Unmarshal(raw, &crd); err != nil {
		t.Fatalf("failed to unmarshal CRD: %v", err)
	}
	return &crd
}

// mcpServerSpecSchema returns the spec subschema from the served+stored
// MCPServer CRD version.
func mcpServerSpecSchema(t *testing.T, crd *apiextensionsv1.CustomResourceDefinition) *apiextensionsv1.JSONSchemaProps {
	t.Helper()
	for _, v := range crd.Spec.Versions {
		if !v.Storage {
			continue
		}
		if v.Schema == nil || v.Schema.OpenAPIV3Schema == nil {
			t.Fatalf("storage version %s has no schema", v.Name)
		}
		spec, ok := v.Schema.OpenAPIV3Schema.Properties["spec"]
		if !ok {
			t.Fatalf("storage version %s schema has no 'spec' property", v.Name)
		}
		return &spec
	}
	t.Fatalf("no storage version found in CRD")
	return nil
}

// TestMCPServerCRD_TransportSchema asserts TB-0 (revised 2026-04-29 — explicit
// fields): the generated CRD YAML declares spec.transport with the
// discriminator type and the explicit mcp/dex sub-objects, each carrying
// `appName` (regex-validated) and `identitySecretRef`.
//
// Spec coverage:
//   - schema declares: transport unset (top-level field is optional)
//   - schema declares: transport.type=teleport with mcp+dex targets
//   - schema declares: kubebuilder enum on transport.type
//   - schema declares: appName regex-pattern on both mcp and dex
//   - schema declares: identitySecretRef as required on both targets
func TestMCPServerCRD_TransportSchema(t *testing.T) {
	crd := loadGeneratedMCPServerCRD(t)
	specSchema := mcpServerSpecSchema(t, crd)

	transport, ok := specSchema.Properties["transport"]
	if !ok {
		t.Fatalf("spec.transport is missing from generated CRD schema")
	}

	// transport.type must be a required, enum-restricted field.
	requiredTransportFields := map[string]bool{}
	for _, f := range transport.Required {
		requiredTransportFields[f] = true
	}
	if !requiredTransportFields["type"] {
		t.Errorf("transport.type should be required; required=%v", transport.Required)
	}

	transportType, ok := transport.Properties["type"]
	if !ok {
		t.Fatalf("transport.type missing from schema")
	}
	if got := enumValues(transportType.Enum); !equalSets(got, []string{"teleport"}) {
		t.Errorf("transport.type enum = %v, want [teleport]", got)
	}

	teleport, ok := transport.Properties["teleport"]
	if !ok {
		t.Fatalf("transport.teleport missing from schema")
	}
	teleportRequired := map[string]bool{}
	for _, f := range teleport.Required {
		teleportRequired[f] = true
	}
	// mcp is required; dex is optional (CEL guards the tokenExchange case).
	if !teleportRequired["mcp"] {
		t.Errorf("transport.teleport.mcp should be required; required=%v", teleport.Required)
	}
	if teleportRequired["dex"] {
		t.Errorf("transport.teleport.dex must remain optional (only required via CEL when tokenExchange.enabled=true); required=%v", teleport.Required)
	}

	// Both mcp and dex must declare the same shape: appName + identitySecretRef.
	for _, name := range []string{"mcp", "dex"} {
		target, ok := teleport.Properties[name]
		if !ok {
			t.Fatalf("transport.teleport.%s missing from schema", name)
		}
		req := map[string]bool{}
		for _, f := range target.Required {
			req[f] = true
		}
		if !req["appName"] {
			t.Errorf("transport.teleport.%s.appName must be required; required=%v", name, target.Required)
		}
		if !req["identitySecretRef"] {
			t.Errorf("transport.teleport.%s.identitySecretRef must be required; required=%v", name, target.Required)
		}
		appName, ok := target.Properties["appName"]
		if !ok {
			t.Fatalf("transport.teleport.%s.appName missing from schema", name)
		}
		if appName.Pattern == "" {
			t.Errorf("transport.teleport.%s.appName missing pattern", name)
		}
		if !strings.Contains(appName.Pattern, "[a-z") {
			t.Errorf("transport.teleport.%s.appName pattern = %q, want lowercase DNS label", name, appName.Pattern)
		}
		if _, ok := target.Properties["identitySecretRef"]; !ok {
			t.Errorf("transport.teleport.%s.identitySecretRef missing from schema", name)
		}
	}

	// transport itself must NOT be in the spec.required list — preserves
	// customer-Muster (in-VPN) compatibility where the field is omitted.
	for _, f := range specSchema.Required {
		if f == "transport" {
			t.Errorf("spec.transport must remain optional (preserves direct-HTTPS default for customer Muster)")
		}
	}

	// Explicit-fields shape check: the legacy `cluster` field must NOT be
	// present anywhere on transport.teleport.
	if _, present := teleport.Properties["cluster"]; present {
		t.Errorf("transport.teleport.cluster must be removed (replaced by mcp/dex explicit fields)")
	}
}

// TestMCPServerCRD_TransportCELRules asserts TB-0: all four CEL rules are
// declared on the schema. (Compiling and evaluating CEL would require a full
// apiextensions-apiserver harness; this is verified end-to-end at envtest in
// downstream consumers and at apply time in K8s. The reshape PR live-validates
// 8 fixtures against a kind cluster out-of-band.)
//
// Spec coverage (CEL rules present):
//   - transport.type == teleport ↔ transport.teleport != nil
//   - transport forbidden when spec.type == stdio
//   - transport.teleport.dex required when auth.tokenExchange.enabled=true (NEW)
func TestMCPServerCRD_TransportCELRules(t *testing.T) {
	crd := loadGeneratedMCPServerCRD(t)
	for _, v := range crd.Spec.Versions {
		if !v.Storage {
			continue
		}
		root := v.Schema.OpenAPIV3Schema
		rules := celRuleStrings(root.XValidations)

		mustContain(t, rules, "transport.teleport is required when transport.type is teleport")
		mustContain(t, rules, "transport.teleport may only be set when transport.type is teleport")
		mustContain(t, rules, "transport is not allowed when type is stdio")
		mustContain(t, rules, "transport.teleport.dex is required when auth.tokenExchange is enabled")
	}
}

// TestMCPServerCRD_AuthTypeEnum asserts TB-8b: auth.type rejects "teleport".
//
// Spec coverage:
//   - auth.type=teleport: kubebuilder enum rejects (positive assertion).
func TestMCPServerCRD_AuthTypeEnum(t *testing.T) {
	crd := loadGeneratedMCPServerCRD(t)
	specSchema := mcpServerSpecSchema(t, crd)

	auth, ok := specSchema.Properties["auth"]
	if !ok {
		t.Fatalf("spec.auth missing from schema")
	}
	authType, ok := auth.Properties["type"]
	if !ok {
		t.Fatalf("spec.auth.type missing from schema")
	}
	got := enumValues(authType.Enum)
	if !equalSets(got, []string{"oauth", "none"}) {
		t.Errorf("auth.type enum = %v, want [oauth none] (teleport must be removed per TB-8b)", got)
	}
	for _, v := range got {
		if v == "teleport" {
			t.Errorf("auth.type enum still contains 'teleport'; TB-8b removal incomplete")
		}
	}

	// The TeleportAuth field on auth must also be gone.
	if _, present := auth.Properties["teleport"]; present {
		t.Errorf("auth.teleport field still present in schema; TB-8b removal incomplete")
	}
}

// TestMCPServerCRD_NoTeleportAuthDefinition asserts TB-8b: the CRD schema
// no longer references the removed TeleportAuthConfig type anywhere.
func TestMCPServerCRD_NoTeleportAuthDefinition(t *testing.T) {
	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..")
	crdPath := filepath.Join(repoRoot, "helm", "muster", "crds", "muster.giantswarm.io_mcpservers.yaml")

	// #nosec G304 -- crdPath is derived from runtime.Caller, not user input; fixed repo asset.
	raw, err := os.ReadFile(crdPath)
	if err != nil {
		t.Fatalf("failed to read CRD: %v", err)
	}
	if strings.Contains(string(raw), "TeleportAuthConfig") {
		t.Errorf("CRD YAML still references TeleportAuthConfig; TB-8b removal incomplete")
	}
}

// TestMCPServerSpec_TransportRoundTrip asserts the Go struct round-trips via
// YAML across the 8 cases listed in PLAN §6 TB-0 (revised 2026-04-29). For the
// four positive cases we assert presence and correctness of the field. For the
// four reject cases the struct remains buildable (the rejection is enforced by
// CRD validation at apply-time, asserted by TestMCPServerCRD_TransportCELRules
// and verified live against a kind cluster out-of-band).
//
// Cases:
//  1. transport unset                                  → accept (round-trips empty)
//  2. mcp + dex set, tokenExchange enabled             → accept
//  3. mcp-only, dex omitted, tokenExchange disabled    → accept
//  4. transport.type=teleport, no teleport block       → CEL reject (struct compiles)
//  5. transport.type=wireguard (wrong enum)            → reject (kubebuilder enum)
//  6. transport set on spec.type=stdio                 → CEL reject (struct compiles)
//  7. dex omitted while tokenExchange.enabled=true     → CEL reject (NEW rule)
//  8. mcp.appName violates regex (e.g. "MCP_Glean")    → reject (kubebuilder pattern)
func TestMCPServerSpec_TransportRoundTrip(t *testing.T) {
	cases := []struct {
		name     string
		spec     MCPServerSpec
		wantHas  bool
		wantMCP  string
		wantDex  string
		wantSec  string
		wantDexS string
	}{
		{
			name: "1) transport unset (customer Muster default) → accept",
			spec: MCPServerSpec{
				Type: "streamable-http",
				URL:  "https://mcp.example.com",
			},
			wantHas: false,
		},
		{
			name: "2) mcp + dex set, tokenExchange enabled → accept",
			spec: MCPServerSpec{
				Type: "streamable-http",
				URL:  "https://mcp-kubernetes-glean.teleport.giantswarm.io/mcp",
				Auth: &MCPServerAuth{
					Type: "oauth",
					TokenExchange: &TokenExchangeConfig{
						Enabled:          true,
						DexTokenEndpoint: "https://dex-glean.teleport.giantswarm.io/token",
						ConnectorID:      "giantswarm",
					},
				},
				Transport: &MCPServerTransport{
					Type: "teleport",
					Teleport: &TeleportTransport{
						MCP: TeleportTarget{
							AppName: "mcp-kubernetes-glean",
							IdentitySecretRef: corev1.LocalObjectReference{
								Name: "tbot-identity-mcp-glean",
							},
						},
						Dex: &TeleportTarget{
							AppName: "dex-glean",
							IdentitySecretRef: corev1.LocalObjectReference{
								Name: "tbot-identity-tx-glean",
							},
						},
					},
				},
			},
			wantHas:  true,
			wantMCP:  "mcp-kubernetes-glean",
			wantSec:  "tbot-identity-mcp-glean",
			wantDex:  "dex-glean",
			wantDexS: "tbot-identity-tx-glean",
		},
		{
			name: "3) mcp-only, dex omitted, tokenExchange disabled → accept",
			spec: MCPServerSpec{
				Type: "streamable-http",
				URL:  "https://mcp-kubernetes-glean.teleport.giantswarm.io/mcp",
				Auth: &MCPServerAuth{
					Type:         "oauth",
					ForwardToken: true,
				},
				Transport: &MCPServerTransport{
					Type: "teleport",
					Teleport: &TeleportTransport{
						MCP: TeleportTarget{
							AppName: "mcp-kubernetes-glean",
							IdentitySecretRef: corev1.LocalObjectReference{
								Name: "tbot-identity-mcp-glean",
							},
						},
					},
				},
			},
			wantHas: true,
			wantMCP: "mcp-kubernetes-glean",
			wantSec: "tbot-identity-mcp-glean",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			raw, err := yaml.Marshal(&tc.spec)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			var got MCPServerSpec
			if err := yaml.Unmarshal(raw, &got); err != nil {
				t.Fatalf("unmarshal: %v", err)
			}
			if (got.Transport != nil) != tc.wantHas {
				t.Fatalf("transport presence = %v, want %v\nyaml:\n%s", got.Transport != nil, tc.wantHas, raw)
			}
			if !tc.wantHas {
				return
			}
			if got.Transport.Type != "teleport" {
				t.Errorf("transport.type = %q, want teleport", got.Transport.Type)
			}
			if got.Transport.Teleport == nil {
				t.Fatalf("transport.teleport is nil after round-trip\nyaml:\n%s", raw)
			}
			if got.Transport.Teleport.MCP.AppName != tc.wantMCP {
				t.Errorf("transport.teleport.mcp.appName = %q, want %q", got.Transport.Teleport.MCP.AppName, tc.wantMCP)
			}
			if got.Transport.Teleport.MCP.IdentitySecretRef.Name != tc.wantSec {
				t.Errorf("transport.teleport.mcp.identitySecretRef.name = %q, want %q", got.Transport.Teleport.MCP.IdentitySecretRef.Name, tc.wantSec)
			}
			if tc.wantDex == "" {
				if got.Transport.Teleport.Dex != nil {
					t.Errorf("transport.teleport.dex should be nil for mcp-only case, got %+v", got.Transport.Teleport.Dex)
				}
				return
			}
			if got.Transport.Teleport.Dex == nil {
				t.Fatalf("transport.teleport.dex is nil after round-trip\nyaml:\n%s", raw)
			}
			if got.Transport.Teleport.Dex.AppName != tc.wantDex {
				t.Errorf("transport.teleport.dex.appName = %q, want %q", got.Transport.Teleport.Dex.AppName, tc.wantDex)
			}
			if got.Transport.Teleport.Dex.IdentitySecretRef.Name != tc.wantDexS {
				t.Errorf("transport.teleport.dex.identitySecretRef.name = %q, want %q", got.Transport.Teleport.Dex.IdentitySecretRef.Name, tc.wantDexS)
			}
		})
	}
}

// TestMCPServerAuth_NoTeleportField confirms the Go struct has no Teleport
// field on MCPServerAuth (TB-8b removal).
func TestMCPServerAuth_NoTeleportField(t *testing.T) {
	// Compile-time: if MCPServerAuth.Teleport existed, this file would not
	// compile after the removal. We assert presence of the surviving fields
	// to give a clear failure message if someone re-adds it.
	_ = MCPServerAuth{
		Type:              "oauth",
		ForwardToken:      true,
		RequiredAudiences: nil,
		TokenExchange:     nil,
	}
}

// --- helpers ---

func enumValues(in []apiextensionsv1.JSON) []string {
	out := make([]string, 0, len(in))
	for _, j := range in {
		// JSON values are wrapped in quotes for strings, e.g. `"teleport"`.
		s := strings.Trim(string(j.Raw), `"`)
		out = append(out, s)
	}
	return out
}

func equalSets(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	seen := map[string]int{}
	for _, x := range a {
		seen[x]++
	}
	for _, x := range b {
		seen[x]--
	}
	for _, n := range seen {
		if n != 0 {
			return false
		}
	}
	return true
}

func celRuleStrings(in []apiextensionsv1.ValidationRule) []string {
	out := make([]string, 0, len(in))
	for _, r := range in {
		out = append(out, r.Rule+" || "+r.Message)
	}
	return out
}

func mustContain(t *testing.T, haystack []string, needle string) {
	t.Helper()
	for _, h := range haystack {
		if strings.Contains(h, needle) {
			return
		}
	}
	t.Errorf("expected CEL rule containing %q\nrules:\n  %s", needle, strings.Join(haystack, "\n  "))
}
