package v1alpha1

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"
)

// loadGeneratedMCPServerCRD reads the generated CRD YAML from helm/muster/crds.
// The CRD file is the single source of truth checked into the repo and is
// regenerated by `make generate-crds`. These tests assert that the generated
// schema enforces what TB-0 and TB-8b promise.
func loadGeneratedMCPServerCRD(t *testing.T) *apiextensionsv1.CustomResourceDefinition {
	t.Helper()

	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..")
	crdPath := filepath.Join(repoRoot, "helm", "muster", "crds", "muster.giantswarm.io_mcpservers.yaml")

	// #nosec G304 -- crdPath is derived from runtime.Caller, not user input; fixed repo asset.
	raw, err := os.ReadFile(crdPath)
	if err != nil {
		t.Fatalf("failed to read CRD %s: %v", crdPath, err)
	}

	var crd apiextensionsv1.CustomResourceDefinition
	if err := yaml.Unmarshal(raw, &crd); err != nil {
		t.Fatalf("failed to unmarshal CRD: %v", err)
	}
	return &crd
}

// mcpServerSpecSchema returns the spec subschema from the served+stored
// MCPServer CRD version.
func mcpServerSpecSchema(t *testing.T, crd *apiextensionsv1.CustomResourceDefinition) *apiextensionsv1.JSONSchemaProps {
	t.Helper()
	for _, v := range crd.Spec.Versions {
		if !v.Storage {
			continue
		}
		if v.Schema == nil || v.Schema.OpenAPIV3Schema == nil {
			t.Fatalf("storage version %s has no schema", v.Name)
		}
		spec, ok := v.Schema.OpenAPIV3Schema.Properties["spec"]
		if !ok {
			t.Fatalf("storage version %s schema has no 'spec' property", v.Name)
		}
		return &spec
	}
	t.Fatalf("no storage version found in CRD")
	return nil
}

// TestMCPServerCRD_TransportSchema asserts the reshape (May 2026): the
// generated CRD declares spec.transport with the discriminator type
// (default=http, enum=[http,teleport]) and a single teleport block carrying
// `appName` (regex-validated) + `identitySecretRef`. The previous mcp/dex
// split is gone — the token-exchange path now declares its own transport
// independently (asserted in TestMCPServerCRD_TokenExchangeTransportSchema).
//
// Spec coverage:
//   - schema declares: transport unset (top-level field is optional)
//   - schema declares: transport.type enum=[http,teleport] with default=http
//   - schema declares: transport.teleport flat with appName+identitySecretRef
//   - schema declares: appName regex-pattern (DNS label)
//   - schema declares: identitySecretRef as required
func TestMCPServerCRD_TransportSchema(t *testing.T) {
	crd := loadGeneratedMCPServerCRD(t)
	specSchema := mcpServerSpecSchema(t, crd)

	transport, ok := specSchema.Properties["transport"]
	if !ok {
		t.Fatalf("spec.transport is missing from generated CRD schema")
	}

	// transport.type must be a required, enum-restricted field.
	requiredTransportFields := map[string]bool{}
	for _, f := range transport.Required {
		requiredTransportFields[f] = true
	}
	if !requiredTransportFields["type"] {
		t.Errorf("transport.type should be required; required=%v", transport.Required)
	}

	transportType, ok := transport.Properties["type"]
	if !ok {
		t.Fatalf("transport.type missing from schema")
	}
	if got := enumValues(transportType.Enum); !equalSets(got, []string{"http", "teleport"}) {
		t.Errorf("transport.type enum = %v, want [http teleport]", got)
	}
	// Default must be http (so omitted == direct HTTPS).
	if transportType.Default == nil {
		t.Errorf("transport.type missing default; want default=http")
	} else if got := strings.Trim(string(transportType.Default.Raw), `"`); got != "http" {
		t.Errorf("transport.type default = %q, want %q", got, "http")
	}

	teleport, ok := transport.Properties["teleport"]
	if !ok {
		t.Fatalf("transport.teleport missing from schema")
	}
	teleportRequired := map[string]bool{}
	for _, f := range teleport.Required {
		teleportRequired[f] = true
	}
	// Single flat target now: appName + identitySecretRef both required.
	if !teleportRequired["appName"] {
		t.Errorf("transport.teleport.appName should be required; required=%v", teleport.Required)
	}
	if !teleportRequired["identitySecretRef"] {
		t.Errorf("transport.teleport.identitySecretRef should be required; required=%v", teleport.Required)
	}

	appName, ok := teleport.Properties["appName"]
	if !ok {
		t.Fatalf("transport.teleport.appName missing from schema")
	}
	if appName.Pattern == "" {
		t.Errorf("transport.teleport.appName missing pattern")
	}
	if !strings.Contains(appName.Pattern, "[a-z") {
		t.Errorf("transport.teleport.appName pattern = %q, want lowercase DNS label", appName.Pattern)
	}
	if _, ok := teleport.Properties["identitySecretRef"]; !ok {
		t.Errorf("transport.teleport.identitySecretRef missing from schema")
	}

	// The previous {mcp, dex} split must be gone — the token-exchange
	// transport is now under spec.auth.tokenExchange.transport.
	if _, present := teleport.Properties["mcp"]; present {
		t.Errorf("transport.teleport.mcp must be removed (collapsed to single target)")
	}
	if _, present := teleport.Properties["dex"]; present {
		t.Errorf("transport.teleport.dex must be removed (replaced by auth.tokenExchange.transport)")
	}

	// transport itself must NOT be in the spec.required list — preserves
	// customer-Muster (in-VPN) compatibility where the field is omitted.
	for _, f := range specSchema.Required {
		if f == "transport" {
			t.Errorf("spec.transport must remain optional (preserves direct-HTTPS default for customer Muster)")
		}
	}
}

// TestMCPServerCRD_TokenExchangeSchema asserts the reshape: the generated
// CRD declares spec.auth.tokenExchange with the new provider-neutral
// shape — `tokenEndpoint`, `provider` discriminator (default=dex), nested
// `dex.connectorId`, and a per-tokenExchange `transport` block.
func TestMCPServerCRD_TokenExchangeSchema(t *testing.T) {
	crd := loadGeneratedMCPServerCRD(t)
	specSchema := mcpServerSpecSchema(t, crd)

	auth, ok := specSchema.Properties["auth"]
	if !ok {
		t.Fatalf("spec.auth missing from schema")
	}
	tx, ok := auth.Properties["tokenExchange"]
	if !ok {
		t.Fatalf("spec.auth.tokenExchange missing from schema")
	}

	// Renamed: dexTokenEndpoint → tokenEndpoint.
	if _, present := tx.Properties["dexTokenEndpoint"]; present {
		t.Errorf("auth.tokenExchange.dexTokenEndpoint must be removed (renamed to tokenEndpoint)")
	}
	if _, present := tx.Properties["tokenEndpoint"]; !present {
		t.Errorf("auth.tokenExchange.tokenEndpoint missing from schema")
	}

	// connectorId is no longer flat — moved into nested dex.connectorId.
	if _, present := tx.Properties["connectorId"]; present {
		t.Errorf("auth.tokenExchange.connectorId must be removed (moved under dex)")
	}
	dex, ok := tx.Properties["dex"]
	if !ok {
		t.Fatalf("auth.tokenExchange.dex missing from schema")
	}
	dexRequired := map[string]bool{}
	for _, f := range dex.Required {
		dexRequired[f] = true
	}
	if !dexRequired["connectorId"] {
		t.Errorf("auth.tokenExchange.dex.connectorId should be required; required=%v", dex.Required)
	}

	// Provider discriminator: enum=[dex], default=dex.
	provider, ok := tx.Properties["provider"]
	if !ok {
		t.Fatalf("auth.tokenExchange.provider missing from schema")
	}
	if got := enumValues(provider.Enum); !equalSets(got, []string{"dex"}) {
		t.Errorf("auth.tokenExchange.provider enum = %v, want [dex]", got)
	}
	if provider.Default == nil {
		t.Errorf("auth.tokenExchange.provider missing default; want default=dex")
	} else if got := strings.Trim(string(provider.Default.Raw), `"`); got != "dex" {
		t.Errorf("auth.tokenExchange.provider default = %q, want %q", got, "dex")
	}

	// Per-tokenExchange transport block, mirroring spec.transport.
	transport, ok := tx.Properties["transport"]
	if !ok {
		t.Fatalf("auth.tokenExchange.transport missing from schema")
	}
	transportType, ok := transport.Properties["type"]
	if !ok {
		t.Fatalf("auth.tokenExchange.transport.type missing from schema")
	}
	if got := enumValues(transportType.Enum); !equalSets(got, []string{"http", "teleport"}) {
		t.Errorf("auth.tokenExchange.transport.type enum = %v, want [http teleport]", got)
	}
}

// TestMCPServerCRD_TransportCELRules asserts the CEL rules declared on the
// schema after the reshape. Compiling and evaluating CEL would require a
// full apiextensions-apiserver harness; this is verified end-to-end at
// envtest in downstream consumers and at apply time in K8s.
//
// Spec coverage (CEL rules present):
//   - transport.type == teleport ↔ transport.teleport != nil
//   - transport forbidden when spec.type == stdio
//   - same shape applied to auth.tokenExchange.transport
//   - auth.tokenExchange.dex.connectorId required when enabled with provider=dex
func TestMCPServerCRD_TransportCELRules(t *testing.T) {
	crd := loadGeneratedMCPServerCRD(t)
	for _, v := range crd.Spec.Versions {
		if !v.Storage {
			continue
		}
		root := v.Schema.OpenAPIV3Schema
		rules := celRuleStrings(root.XValidations)

		mustContain(t, rules, "transport.teleport is required when transport.type is teleport")
		mustContain(t, rules, "transport.teleport may only be set when transport.type is teleport")
		mustContain(t, rules, "transport is not allowed when type is stdio")
		mustContain(t, rules, "auth.tokenExchange.transport.teleport is required when auth.tokenExchange.transport.type is teleport")
		mustContain(t, rules, "auth.tokenExchange.transport.teleport may only be set when auth.tokenExchange.transport.type is teleport")
		mustContain(t, rules, "auth.tokenExchange.dex.connectorId is required when auth.tokenExchange.enabled and provider is dex")
	}
}

// TestMCPServerCRD_AuthTypeEnum asserts TB-8b: auth.type rejects "teleport".
//
// Spec coverage:
//   - auth.type=teleport: kubebuilder enum rejects (positive assertion).
func TestMCPServerCRD_AuthTypeEnum(t *testing.T) {
	crd := loadGeneratedMCPServerCRD(t)
	specSchema := mcpServerSpecSchema(t, crd)

	auth, ok := specSchema.Properties["auth"]
	if !ok {
		t.Fatalf("spec.auth missing from schema")
	}
	authType, ok := auth.Properties["type"]
	if !ok {
		t.Fatalf("spec.auth.type missing from schema")
	}
	got := enumValues(authType.Enum)
	if !equalSets(got, []string{"oauth", "none"}) {
		t.Errorf("auth.type enum = %v, want [oauth none] (teleport must be removed per TB-8b)", got)
	}
	for _, v := range got {
		if v == "teleport" {
			t.Errorf("auth.type enum still contains 'teleport'; TB-8b removal incomplete")
		}
	}

	// The TeleportAuth field on auth must also be gone.
	if _, present := auth.Properties["teleport"]; present {
		t.Errorf("auth.teleport field still present in schema; TB-8b removal incomplete")
	}
}

// TestMCPServerCRD_NoTeleportAuthDefinition asserts TB-8b: the CRD schema
// no longer references the removed TeleportAuthConfig type anywhere.
func TestMCPServerCRD_NoTeleportAuthDefinition(t *testing.T) {
	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..")
	crdPath := filepath.Join(repoRoot, "helm", "muster", "crds", "muster.giantswarm.io_mcpservers.yaml")

	// #nosec G304 -- crdPath is derived from runtime.Caller, not user input; fixed repo asset.
	raw, err := os.ReadFile(crdPath)
	if err != nil {
		t.Fatalf("failed to read CRD: %v", err)
	}
	if strings.Contains(string(raw), "TeleportAuthConfig") {
		t.Errorf("CRD YAML still references TeleportAuthConfig; TB-8b removal incomplete")
	}
}

// TestMCPServerSpec_TransportRoundTrip asserts the Go struct round-trips via
// YAML for the new (post-reshape) shape. The two transports are independent:
// spec.transport is for the MCP endpoint only; the token-exchange path
// declares its own transport under spec.auth.tokenExchange.transport.
func TestMCPServerSpec_TransportRoundTrip(t *testing.T) {
	cases := []struct {
		name        string
		spec        MCPServerSpec
		wantTeleS   bool
		wantMCP     string
		wantSec     string
		wantTxTeleS bool
		wantTxApp   string
		wantTxSec   string
	}{
		{
			name: "transport unset (customer Muster default) → accept",
			spec: MCPServerSpec{
				Type: "streamable-http",
				URL:  "https://mcp.example.com",
			},
		},
		{
			name: "two independent teleport transports — MCP + tokenExchange",
			spec: MCPServerSpec{
				Type: "streamable-http",
				URL:  "https://mcp-kubernetes-glean.teleport.giantswarm.io/mcp",
				Auth: &MCPServerAuth{
					Type: "oauth",
					// #nosec G101 -- test fixture; not a credential.
					TokenExchange: &TokenExchangeConfig{
						Enabled:       true,
						TokenEndpoint: "https://dex-glean.teleport.giantswarm.io/token",
						Provider:      "dex",
						Dex: &DexTokenExchangeConfig{
							ConnectorID: "giantswarm",
						},
						Transport: &MCPServerTransport{
							Type: "teleport",
							Teleport: &TeleportTransport{
								AppName: "dex-glean",
								IdentitySecretRef: corev1.LocalObjectReference{
									Name: "tbot-identity-tx-glean",
								},
							},
						},
					},
				},
				Transport: &MCPServerTransport{
					Type: "teleport",
					Teleport: &TeleportTransport{
						AppName: "mcp-kubernetes-glean",
						IdentitySecretRef: corev1.LocalObjectReference{
							Name: "tbot-identity-mcp-glean",
						},
					},
				},
			},
			wantTeleS:   true,
			wantMCP:     "mcp-kubernetes-glean",
			wantSec:     "tbot-identity-mcp-glean",
			wantTxTeleS: true,
			wantTxApp:   "dex-glean",
			wantTxSec:   "tbot-identity-tx-glean",
		},
		{
			name: "MCP-only teleport, tokenExchange disabled (forwardToken path)",
			spec: MCPServerSpec{
				Type: "streamable-http",
				URL:  "https://mcp-kubernetes-glean.teleport.giantswarm.io/mcp",
				Auth: &MCPServerAuth{
					Type:         "oauth",
					ForwardToken: true,
				},
				Transport: &MCPServerTransport{
					Type: "teleport",
					Teleport: &TeleportTransport{
						AppName: "mcp-kubernetes-glean",
						IdentitySecretRef: corev1.LocalObjectReference{
							Name: "tbot-identity-mcp-glean",
						},
					},
				},
			},
			wantTeleS: true,
			wantMCP:   "mcp-kubernetes-glean",
			wantSec:   "tbot-identity-mcp-glean",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			raw, err := yaml.Marshal(&tc.spec)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			var got MCPServerSpec
			if err := yaml.Unmarshal(raw, &got); err != nil {
				t.Fatalf("unmarshal: %v", err)
			}

			// spec.transport assertions
			if (got.Transport != nil && got.Transport.Teleport != nil) != tc.wantTeleS {
				t.Fatalf("spec.transport.teleport presence = %v, want %v\nyaml:\n%s",
					got.Transport != nil && got.Transport.Teleport != nil, tc.wantTeleS, raw)
			}
			if tc.wantTeleS {
				if got.Transport.Type != "teleport" {
					t.Errorf("spec.transport.type = %q, want teleport", got.Transport.Type)
				}
				if got.Transport.Teleport.AppName != tc.wantMCP {
					t.Errorf("spec.transport.teleport.appName = %q, want %q", got.Transport.Teleport.AppName, tc.wantMCP)
				}
				if got.Transport.Teleport.IdentitySecretRef.Name != tc.wantSec {
					t.Errorf("spec.transport.teleport.identitySecretRef.name = %q, want %q", got.Transport.Teleport.IdentitySecretRef.Name, tc.wantSec)
				}
			}

			// spec.auth.tokenExchange.transport assertions
			haveTxTele := got.Auth != nil &&
				got.Auth.TokenExchange != nil &&
				got.Auth.TokenExchange.Transport != nil &&
				got.Auth.TokenExchange.Transport.Teleport != nil
			if haveTxTele != tc.wantTxTeleS {
				t.Fatalf("auth.tokenExchange.transport.teleport presence = %v, want %v\nyaml:\n%s",
					haveTxTele, tc.wantTxTeleS, raw)
			}
			if tc.wantTxTeleS {
				txTele := got.Auth.TokenExchange.Transport.Teleport
				if txTele.AppName != tc.wantTxApp {
					t.Errorf("tokenExchange.transport.teleport.appName = %q, want %q", txTele.AppName, tc.wantTxApp)
				}
				if txTele.IdentitySecretRef.Name != tc.wantTxSec {
					t.Errorf("tokenExchange.transport.teleport.identitySecretRef.name = %q, want %q", txTele.IdentitySecretRef.Name, tc.wantTxSec)
				}
				if got.Auth.TokenExchange.Provider != "dex" {
					t.Errorf("tokenExchange.provider = %q, want %q", got.Auth.TokenExchange.Provider, "dex")
				}
				if got.Auth.TokenExchange.Dex == nil || got.Auth.TokenExchange.Dex.ConnectorID == "" {
					t.Errorf("tokenExchange.dex.connectorId is empty after round-trip")
				}
			}
		})
	}
}

// TestMCPServerAuth_NoTeleportField confirms the Go struct has no Teleport
// field on MCPServerAuth (TB-8b removal).
func TestMCPServerAuth_NoTeleportField(t *testing.T) {
	// Compile-time: if MCPServerAuth.Teleport existed, this file would not
	// compile after the removal. We assert presence of the surviving fields
	// to give a clear failure message if someone re-adds it.
	_ = MCPServerAuth{
		Type:              "oauth",
		ForwardToken:      true,
		RequiredAudiences: nil,
		TokenExchange:     nil,
	}
}

// --- helpers ---

func enumValues(in []apiextensionsv1.JSON) []string {
	out := make([]string, 0, len(in))
	for _, j := range in {
		// JSON values are wrapped in quotes for strings, e.g. `"teleport"`.
		s := strings.Trim(string(j.Raw), `"`)
		out = append(out, s)
	}
	return out
}

func equalSets(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	seen := map[string]int{}
	for _, x := range a {
		seen[x]++
	}
	for _, x := range b {
		seen[x]--
	}
	for _, n := range seen {
		if n != 0 {
			return false
		}
	}
	return true
}

func celRuleStrings(in []apiextensionsv1.ValidationRule) []string {
	out := make([]string, 0, len(in))
	for _, r := range in {
		out = append(out, r.Rule+" || "+r.Message)
	}
	return out
}

func mustContain(t *testing.T, haystack []string, needle string) {
	t.Helper()
	for _, h := range haystack {
		if strings.Contains(h, needle) {
			return
		}
	}
	t.Errorf("expected CEL rule containing %q\nrules:\n  %s", needle, strings.Join(haystack, "\n  "))
}
