package v1alpha1

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"
)

// loadGeneratedMCPServerCRD reads the generated CRD YAML from helm/muster/crds.
// The CRD file is the single source of truth checked into the repo and is
// regenerated by `make generate-crds`. These tests assert that the generated
// schema enforces what TB-0 and TB-8b promise.
func loadGeneratedMCPServerCRD(t *testing.T) *apiextensionsv1.CustomResourceDefinition {
	t.Helper()

	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..")
	crdPath := filepath.Join(repoRoot, "helm", "muster", "crds", "muster.giantswarm.io_mcpservers.yaml")

	raw, err := os.ReadFile(crdPath)
	if err != nil {
		t.Fatalf("failed to read CRD %s: %v", crdPath, err)
	}

	var crd apiextensionsv1.CustomResourceDefinition
	if err := yaml.Unmarshal(raw, &crd); err != nil {
		t.Fatalf("failed to unmarshal CRD: %v", err)
	}
	return &crd
}

// mcpServerSpecSchema returns the spec subschema from the served+stored
// MCPServer CRD version.
func mcpServerSpecSchema(t *testing.T, crd *apiextensionsv1.CustomResourceDefinition) *apiextensionsv1.JSONSchemaProps {
	t.Helper()
	for _, v := range crd.Spec.Versions {
		if !v.Storage {
			continue
		}
		if v.Schema == nil || v.Schema.OpenAPIV3Schema == nil {
			t.Fatalf("storage version %s has no schema", v.Name)
		}
		spec, ok := v.Schema.OpenAPIV3Schema.Properties["spec"]
		if !ok {
			t.Fatalf("storage version %s schema has no 'spec' property", v.Name)
		}
		return &spec
	}
	t.Fatalf("no storage version found in CRD")
	return nil
}

// TestMCPServerCRD_TransportSchema asserts TB-0: the generated CRD YAML
// declares spec.transport with the expected discriminator + cluster fields.
//
// Spec coverage:
//   - schema validates: transport unset (top-level field is optional)
//   - schema validates: transport.type=teleport with teleport.cluster=glean
//   - kubebuilder enum rejects: transport.type=<wrong value>
//   - schema validates: cluster matches the lowercase pattern
func TestMCPServerCRD_TransportSchema(t *testing.T) {
	crd := loadGeneratedMCPServerCRD(t)
	specSchema := mcpServerSpecSchema(t, crd)

	transport, ok := specSchema.Properties["transport"]
	if !ok {
		t.Fatalf("spec.transport is missing from generated CRD schema")
	}

	// transport.type must be a required, enum-restricted field.
	requiredTransportFields := map[string]bool{}
	for _, f := range transport.Required {
		requiredTransportFields[f] = true
	}
	if !requiredTransportFields["type"] {
		t.Errorf("transport.type should be required; required=%v", transport.Required)
	}

	transportType, ok := transport.Properties["type"]
	if !ok {
		t.Fatalf("transport.type missing from schema")
	}
	if got := enumValues(transportType.Enum); !equalSets(got, []string{"teleport"}) {
		t.Errorf("transport.type enum = %v, want [teleport]", got)
	}

	// transport.teleport.cluster must be required + lowercase-pattern.
	teleport, ok := transport.Properties["teleport"]
	if !ok {
		t.Fatalf("transport.teleport missing from schema")
	}
	teleportRequired := map[string]bool{}
	for _, f := range teleport.Required {
		teleportRequired[f] = true
	}
	if !teleportRequired["cluster"] {
		t.Errorf("transport.teleport.cluster should be required; required=%v", teleport.Required)
	}
	cluster, ok := teleport.Properties["cluster"]
	if !ok {
		t.Fatalf("transport.teleport.cluster missing from schema")
	}
	if cluster.Pattern == "" {
		t.Errorf("transport.teleport.cluster missing pattern")
	}
	if !strings.Contains(cluster.Pattern, "[a-z") {
		t.Errorf("transport.teleport.cluster pattern = %q, want lowercase", cluster.Pattern)
	}

	// transport itself must NOT be in the spec.required list — preserves
	// customer-Muster (in-VPN) compatibility where the field is omitted.
	for _, f := range specSchema.Required {
		if f == "transport" {
			t.Errorf("spec.transport must remain optional (preserves direct-HTTPS default for customer Muster)")
		}
	}
}

// TestMCPServerCRD_TransportCELRules asserts TB-0: the three CEL rules are
// declared on the schema. (Compiling and evaluating CEL would require a full
// apiextensions-apiserver harness; this is verified end-to-end at envtest in
// downstream consumers and at apply time in K8s.)
//
// Spec coverage (CEL rules present):
//   - transport.type == teleport ↔ transport.teleport != nil
//   - transport forbidden when spec.type == stdio
func TestMCPServerCRD_TransportCELRules(t *testing.T) {
	crd := loadGeneratedMCPServerCRD(t)
	for _, v := range crd.Spec.Versions {
		if !v.Storage {
			continue
		}
		root := v.Schema.OpenAPIV3Schema
		rules := celRuleStrings(root.XValidations)

		mustContain(t, rules, "transport.teleport is required when transport.type is teleport")
		mustContain(t, rules, "transport.teleport may only be set when transport.type is teleport")
		mustContain(t, rules, "transport is not allowed when type is stdio")
	}
}

// TestMCPServerCRD_AuthTypeEnum asserts TB-8b: auth.type rejects "teleport".
//
// Spec coverage:
//   - auth.type=teleport: kubebuilder enum rejects (positive assertion).
func TestMCPServerCRD_AuthTypeEnum(t *testing.T) {
	crd := loadGeneratedMCPServerCRD(t)
	specSchema := mcpServerSpecSchema(t, crd)

	auth, ok := specSchema.Properties["auth"]
	if !ok {
		t.Fatalf("spec.auth missing from schema")
	}
	authType, ok := auth.Properties["type"]
	if !ok {
		t.Fatalf("spec.auth.type missing from schema")
	}
	got := enumValues(authType.Enum)
	if !equalSets(got, []string{"oauth", "none"}) {
		t.Errorf("auth.type enum = %v, want [oauth none] (teleport must be removed per TB-8b)", got)
	}
	for _, v := range got {
		if v == "teleport" {
			t.Errorf("auth.type enum still contains 'teleport'; TB-8b removal incomplete")
		}
	}

	// The TeleportAuth field on auth must also be gone.
	if _, present := auth.Properties["teleport"]; present {
		t.Errorf("auth.teleport field still present in schema; TB-8b removal incomplete")
	}
}

// TestMCPServerCRD_NoTeleportAuthDefinition asserts TB-8b: the CRD schema
// no longer references the removed TeleportAuthConfig type anywhere.
func TestMCPServerCRD_NoTeleportAuthDefinition(t *testing.T) {
	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..")
	crdPath := filepath.Join(repoRoot, "helm", "muster", "crds", "muster.giantswarm.io_mcpservers.yaml")

	raw, err := os.ReadFile(crdPath)
	if err != nil {
		t.Fatalf("failed to read CRD: %v", err)
	}
	if strings.Contains(string(raw), "TeleportAuthConfig") {
		t.Errorf("CRD YAML still references TeleportAuthConfig; TB-8b removal incomplete")
	}
	// "appName" and "identitySecretName" lived inside the removed legacy
	// TeleportAuthConfig type. Their absence on auth.* confirms removal.
	// (We can't grep the whole file for these strings since they may legitimately
	// be re-introduced under spec.transport.* in future. Schema-level checks
	// above are the canonical assertion.)
}

// TestMCPServerSpec_TransportRoundTrip asserts the Go struct round-trips via
// YAML for both the empty and populated transport cases. This confirms the
// kubebuilder tags we ship don't accidentally drop the field on serialization.
func TestMCPServerSpec_TransportRoundTrip(t *testing.T) {
	cases := []struct {
		name     string
		spec     MCPServerSpec
		wantHas  bool
		wantClus string
	}{
		{
			name: "transport unset (customer Muster default)",
			spec: MCPServerSpec{
				Type: "streamable-http",
				URL:  "https://mcp.example.com",
			},
			wantHas: false,
		},
		{
			name: "transport teleport with cluster",
			spec: MCPServerSpec{
				Type: "streamable-http",
				URL:  "https://mcp-glean.teleport.giantswarm.io/mcp",
				Transport: &MCPServerTransport{
					Type: "teleport",
					Teleport: &TeleportTransport{
						Cluster: "glean",
					},
				},
			},
			wantHas:  true,
			wantClus: "glean",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			raw, err := yaml.Marshal(&tc.spec)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			var got MCPServerSpec
			if err := yaml.Unmarshal(raw, &got); err != nil {
				t.Fatalf("unmarshal: %v", err)
			}
			if (got.Transport != nil) != tc.wantHas {
				t.Fatalf("transport presence = %v, want %v\nyaml:\n%s", got.Transport != nil, tc.wantHas, raw)
			}
			if tc.wantHas {
				if got.Transport.Type != "teleport" {
					t.Errorf("transport.type = %q, want teleport", got.Transport.Type)
				}
				if got.Transport.Teleport == nil || got.Transport.Teleport.Cluster != tc.wantClus {
					t.Errorf("transport.teleport.cluster = %+v, want %q", got.Transport.Teleport, tc.wantClus)
				}
			}
		})
	}
}

// TestMCPServerAuth_NoTeleportField confirms the Go struct has no Teleport
// field on MCPServerAuth (TB-8b removal).
func TestMCPServerAuth_NoTeleportField(t *testing.T) {
	// Compile-time: if MCPServerAuth.Teleport existed, this file would not
	// compile after the removal. We assert presence of the surviving fields
	// to give a clear failure message if someone re-adds it.
	_ = MCPServerAuth{
		Type:              "oauth",
		ForwardToken:      true,
		RequiredAudiences: nil,
		TokenExchange:     nil,
	}
}

// --- helpers ---

func enumValues(in []apiextensionsv1.JSON) []string {
	out := make([]string, 0, len(in))
	for _, j := range in {
		// JSON values are wrapped in quotes for strings, e.g. `"teleport"`.
		s := strings.Trim(string(j.Raw), `"`)
		out = append(out, s)
	}
	return out
}

func equalSets(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	seen := map[string]int{}
	for _, x := range a {
		seen[x]++
	}
	for _, x := range b {
		seen[x]--
	}
	for _, n := range seen {
		if n != 0 {
			return false
		}
	}
	return true
}

func celRuleStrings(in []apiextensionsv1.ValidationRule) []string {
	out := make([]string, 0, len(in))
	for _, r := range in {
		out = append(out, r.Rule+" || "+r.Message)
	}
	return out
}

func mustContain(t *testing.T, haystack []string, needle string) {
	t.Helper()
	for _, h := range haystack {
		if strings.Contains(h, needle) {
			return
		}
	}
	t.Errorf("expected CEL rule containing %q\nrules:\n  %s", needle, strings.Join(haystack, "\n  "))
}
