# Example MCP Server Configurations

# Git tools MCP server (stdio)
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: git-tools
  namespace: default
spec:
  type: stdio
  autoStart: true
  command: npx
  args: ["@modelcontextprotocol/server-git"]
  env:
    GIT_ROOT: "/workspace"
    LOG_LEVEL: "info"
  description: "Git tools MCP server for repository operations"

---
# Filesystem tools MCP server (stdio)
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: filesystem-tools
  namespace: default
spec:
  type: stdio
  autoStart: false
  command: npx
  args: ["@modelcontextprotocol/server-filesystem", "/workspace"]
  env:
    LOG_LEVEL: "debug"
  description: "Filesystem tools MCP server for file operations"

---
# Python tools MCP server (stdio)
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: python-tools
  namespace: default
spec:
  type: stdio
  autoStart: true
  command: python
  args: ["-m", "mcp_server.example"]
  env:
    PYTHONPATH: "/usr/local/lib/python3.9/site-packages"
    DEBUG: "true"
  description: "Python-based MCP server providing custom tools"

---
# Remote MCP server (streamable-http)
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: remote-api-tools
  namespace: default
spec:
  type: streamable-http
  url: "https://api.example.com/mcp"
  timeout: 30
  headers:
    Authorization: "Bearer your-token-here"
    Content-Type: "application/json"
  description: "Remote MCP server providing API tools"

---
# Remote MCP server (sse)
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: remote-sse-tools
  namespace: default
spec:
  type: sse
  url: "https://sse.example.com/mcp"
  timeout: 60
  headers:
    Authorization: "Bearer your-token-here"
  toolPrefix: "remote_"
  description: "Remote MCP server with SSE transport"

---
# Kubernetes MCP server with SSO via token forwarding
# This example demonstrates using requiredAudiences for Kubernetes OIDC authentication
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: mcp-kubernetes
  namespace: default
spec:
  type: streamable-http
  url: "https://mcp-kubernetes.example.com/mcp"
  timeout: 30
  toolPrefix: "k8s"
  description: "Kubernetes MCP server with SSO authentication"
  auth:
    type: oauth
    # Forward muster's ID token to the downstream server
    forwardToken: true
    # Request additional audiences for Kubernetes OIDC authentication
    # This causes muster to request "audience:server:client_id:dex-k8s-authenticator"
    # from Dex, resulting in an ID token that Kubernetes will accept
    requiredAudiences:
      - "dex-k8s-authenticator"
    # If token forwarding fails (e.g., audience mismatch), trigger separate auth
    fallbackToOwnAuth: true
