# Example MCP Server Configurations

# Git tools MCP server (local)
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: git-tools
  namespace: default
spec:
  type: local
  local:
    autoStart: true
    command: ["npx", "@modelcontextprotocol/server-git"]
    env:
      GIT_ROOT: "/workspace"
      LOG_LEVEL: "info"
  description: "Git tools MCP server for repository operations"

---
# Filesystem tools MCP server (local)
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: filesystem-tools
  namespace: default
spec:
  type: local
  local:
    autoStart: false
    command: ["npx", "@modelcontextprotocol/server-filesystem", "/workspace"]
    env:
      LOG_LEVEL: "debug"
  description: "Filesystem tools MCP server for file operations"

---
# Python tools MCP server (local)
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: python-tools
  namespace: default
spec:
  type: local
  local:
    autoStart: true
    command: ["python", "-m", "mcp_server.example"]
    env:
      PYTHONPATH: "/usr/local/lib/python3.9/site-packages"
      DEBUG: "true"
  description: "Python-based MCP server providing custom tools"

---
# Remote MCP server (HTTP)
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: remote-api-tools
  namespace: default
spec:
  type: remote
  remote:
    endpoint: "https://api.example.com/mcp"
    transport: "http"
    timeout: 30
  description: "Remote MCP server providing API tools"

---
# Remote MCP server (SSE)
apiVersion: muster.giantswarm.io/v1alpha1
kind: MCPServer
metadata:
  name: remote-sse-tools
  namespace: default
spec:
  type: remote
  remote:
    endpoint: "https://sse.example.com/mcp"
    transport: "sse"
    timeout: 60
  toolPrefix: "remote_"
  description: "Remote MCP server with SSE transport" 
