apiVersion: muster.giantswarm.io/v1alpha1
kind: Workflow
metadata:
  name: complex-deployment
  namespace: default
spec:
  description: "Database migration workflow with rollback capability and validation"
  args:
    migration_version:
      type: string
      required: true
      description: "Version to migrate to"
    dry_run:
      type: boolean
      default: false
      description: "Perform dry run without applying changes"
    force_rollback:
      type: boolean
      default: false
      description: "Force rollback on any failure"
    backup_retention:
      type: string
      default: "30d"
      description: "How long to retain the backup"
  steps:
    - id: backup_database
      tool: db_backup
      args:
        backup_name: "pre-migration-{{.migration_version}}"
        retention: "{{.backup_retention}}"
      store: true
    
    - id: validate_migration
      tool: db_validate_migration
      args:
        version: "{{.migration_version}}"
        dry_run: "{{.dry_run}}"
      store: true
    
    - id: apply_migration
      tool: db_apply_migration
      args:
        version: "{{.migration_version}}"
        dry_run: "{{.dry_run}}"
      store: true
      allowFailure: true
    
    - id: rollback_on_failure
      tool: db_rollback
      args:
        backup_name: "{{.results.backup_database.backup_id}}"
      condition:
        fromStep: "apply_migration"
        expect:
          success: false
      store: true 