apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muster.fullname" . }}-config
  labels:
    {{- include "muster.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "muster.config" . | nindent 4 }}
