apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muster.fullname" . }}
  labels:
    {{- include "muster.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "muster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Force pod restart on config changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "muster.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "muster.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "muster.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "muster"
          args:
            - "serve"
            - "--config-path={{ .Values.muster.configPath }}"
            {{- if .Values.muster.debug }}
            - "--debug"
            {{- end }}
            {{- if .Values.muster.yolo }}
            - "--yolo"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.muster.aggregator.port }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            - name: muster-config
              mountPath: {{ .Values.muster.configPath }}/config.yaml
              subPath: config.yaml
              readOnly: true
          env:
            - name: MUSTER_CONFIG_PATH
              value: {{ .Values.muster.configPath | quote }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
        - name: muster-config
          configMap:
            name: {{ include "muster.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
