{{- if and .Values.muster.oauth.server.enabled (not .Values.muster.oauth.server.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "muster.fullname" . }}-oauth
  labels:
    {{- include "muster.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "muster.oauthSecretData" . | nindent 2 }}
{{- end }}
