#!/bin/bash
# Install git hooks for muster development
#
# Usage: ./scripts/install-hooks.sh
# Or:    make install-hooks

set -e

HOOKS_DIR="$(git rev-parse --git-dir)/hooks"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Installing git hooks..."

# Create pre-commit hook
cat > "$HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/bash
# Auto-generated by scripts/install-hooks.sh
# Regenerate CRDs if API types changed

# Check if any pkg/apis/*.go files are staged
if git diff --cached --name-only | grep -q '^pkg/apis/.*\.go$'; then
    echo "API types changed, regenerating CRDs..."
    make generate-crds
    
    # Stage the regenerated CRDs
    git add helm/muster/crds/*.yaml
    
    echo "CRDs regenerated and staged."
fi
EOF

chmod +x "$HOOKS_DIR/pre-commit"

echo "Git hooks installed successfully."
echo "The pre-commit hook will automatically regenerate CRDs when API types change."
